import initialSetup from "../../config/initialDBSetup/usersSetup";
import apiResponseLogSetup from "../../config/initialDBSetup/apiResponseLogSetup";
import driverDetailsSetup from "../../config/initialDBSetup/driverDetailsSetup";
import driverLocationsSetup from "../../config/initialDBSetup/driverLocationsSetup";
import logisticOrderItemsSetup from "../../config/initialDBSetup/logisticOrderItemsSetup";
import logisticOrderSetup from "../../config/initialDBSetup/logisticOrderSetup";
import logisticPaymentSetup from "../../config/initialDBSetup/logisticPaymentSetup";
import routeSegmentsSetup from "../../config/initialDBSetup/routeSegmentsSetup";
import routeUpdatesSetup from "../../config/initialDBSetup/routeUpdatesSetup";
import solarItemsSetup from "../../config/initialDBSetup/solarmodulesItemsSetup";
import tourDriverSetup from "../../config/initialDBSetup/tourDriverSetup";
import tourInfoMasterSetup from "../../config/initialDBSetup/tourInfoMasterSetup";
import warehouseDetailsSetup from "../../config/initialDBSetup/warehouseDetailsSetup";
import vahicleDetailsSetup from "../../config/initialDBSetup/vehicleDetailsSetup";
import WMSOrderSetup from "../../config/initialDBSetup/wms_orders";
import WMSOrderArticlesSetup from "../../config/initialDBSetup/wms_order_articles";
import WhatsappChatsSetup from "../../config/initialDBSetup/whatsappChat";
import NotificationsTrackSetup from "../../config/initialDBSetup/notifications_track";
import DynamicTourSetup from "../../config/initialDBSetup/dynamicTourSetup";
import TourTracesSetup from "../../config/initialDBSetup/tourTracesSetup";
import deliveryCostRatesSetup from "../../config/initialDBSetup/deliveryCostRatesSetup";
import deliveryCostPerTourSetup from "../../config/initialDBSetup/deliveryCostPerTourSetup";
import OrderImagesSetup from "../../config/initialDBSetup/orderImagesSetup";
import returnsSetup from "../../config/initialDBSetup/returnsOrderSetup";
import returnsOrderItemsSetup from "../../config/initialDBSetup/returnsOrderItemsSetup";

export async function runInitialDbSetup() {
  await initialSetup();
  await logisticOrderSetup();
  await logisticPaymentSetup();
  await warehouseDetailsSetup();
  await vahicleDetailsSetup();
  await driverDetailsSetup();
  await tourInfoMasterSetup();
  await driverLocationsSetup();
  await routeSegmentsSetup();
  await WMSOrderSetup();
  await WMSOrderArticlesSetup();
  await tourDriverSetup();
  await logisticOrderItemsSetup();
  await routeUpdatesSetup();
  await apiResponseLogSetup();
  await solarItemsSetup();
  await WhatsappChatsSetup();
  await NotificationsTrackSetup();
  await DynamicTourSetup();
  await TourTracesSetup();
  await deliveryCostRatesSetup();
  await deliveryCostPerTourSetup();
  await OrderImagesSetup();
  await returnsSetup();
  await returnsOrderItemsSetup();
}
