import initialSetup from "../../initialDBSetup/usersSetup";
import apiResponseLogSetup from "../../initialDBSetup/apiResponseLogSetup";
import driverDetailsSetup from "../../initialDBSetup/driverDetailsSetup";
import driverLocationsSetup from "../../initialDBSetup/driverLocationsSetup";
import logisticOrderItemsSetup from "../../initialDBSetup/logisticOrderItemsSetup";
import logisticOrderSetup from "../../initialDBSetup/logisticOrderSetup";
import logisticPaymentSetup from "../../initialDBSetup/logisticPaymentSetup";
import routeSegmentsSetup from "../../initialDBSetup/routeSegmentsSetup";
import routeUpdatesSetup from "../../initialDBSetup/routeUpdatesSetup";
import solarItemsSetup from "../../initialDBSetup/solarmodulesItemsSetup";
import tourDriverSetup from "../../initialDBSetup/tourDriverSetup";
import tourInfoMasterSetup from "../../initialDBSetup/tourInfoMasterSetup";
import warehouseDetailsSetup from "../../initialDBSetup/warehouseDetailsSetup";
import vahicleDetailsSetup from "../../initialDBSetup/vehicleDetailsSetup";
import WMSOrderSetup from "../../initialDBSetup/wms_orders";
import WMSOrderArticlesSetup from "../../initialDBSetup/wms_order_articles";
import WhatsappChatsSetup from "../../initialDBSetup/whatsappChat";
import NotificationsTrackSetup from "../../initialDBSetup/notifications_track";
import DynamicTourSetup from "../../initialDBSetup/dynamicTourSetup";
import TourTracesSetup from "../../initialDBSetup/tourTracesSetup";

export async function runInitialDbSetup() {
  await initialSetup();
  await logisticOrderSetup();
  await logisticPaymentSetup();
  await warehouseDetailsSetup();
  await vahicleDetailsSetup();
  await driverDetailsSetup();
  await tourInfoMasterSetup();
  await driverLocationsSetup();
  await routeSegmentsSetup();
  await WMSOrderSetup();
  await WMSOrderArticlesSetup();
  await tourDriverSetup();
  await logisticOrderItemsSetup();
  await routeUpdatesSetup();
  await apiResponseLogSetup();
  await solarItemsSetup();
  await WhatsappChatsSetup();
  await NotificationsTrackSetup();
  await DynamicTourSetup();
  await TourTracesSetup();
}
